name: Tests

on:
  push:
    branches-ignore:
      - 'main'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18.12
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run test:lint

  ts-check:
    runs-on: ubuntu-latest
    name: Type checking
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18.12
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        run: npm run test:type-check

  unit:
    runs-on: ubuntu-latest
    name: Unit/Integration tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18.12
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Run test runner
        run: npm run test:unit
